site_name: smart-planner Documentation
site_url: https://prakashgbid.github.io/smart-planner/
site_description: Goal-oriented autonomous task planning for AI
site_author: OSA Contributors

repo_name: prakashgbid/smart-planner
repo_url: https://github.com/prakashgbid/smart-planner

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, "src")

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Basic Usage: guide/basic-usage.md
    - Advanced Features: guide/advanced-features.md
    - Best Practices: guide/best-practices.md
  - API Reference:
    - Core Module: api/core.md
    - Types: api/types.md
    - Utils: api/utils.md
  - Examples:
    - Basic Examples: examples/basic.md
    - Advanced Examples: examples/advanced.md
    - Integration Examples: examples/integration.md
  - Contributing:
    - Development Setup: contributing/setup.md
    - Guidelines: contributing/guidelines.md
    - Testing: contributing/testing.md
  - FAQ: faq.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prakashgbid
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/smart-planner/
  analytics:
    provider: google
    property: G-XXXXXXXXXX
